# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import utils.files


class Migration(migrations.Migration):
    replaces = [('mediamanager', '0001_initial'), ('mediamanager', '0002_asset_asset_url'),
                ('mediamanager', '0003_asset_created'), ('mediamanager', '0004_auto_20160728_2311'),
                ('mediamanager', '0005_auto_20160801_0452'),
                ('mediamanager', '0006_auto_20160803_0344'),
                ('mediamanager', '0007_contentfeed_auto_created'),
                ('mediamanager', '0008_playlistitem_auto_add_feeds'),
                ('mediamanager', '0009_feedasset'), ('mediamanager', '0010_auto_20160807_0409'),
                ('mediamanager', '0011_auto_20160807_1608')]

    initial = True

    dependencies = [
        ('feedmanager', '0006_feed_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ContentFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_duration', models.IntegerField(default=4500)),
                ('web_duration', models.IntegerField(default=4500)),
                ('overlay_ticker', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Content Feed',
                'verbose_name_plural': 'Content Feeds',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('text', models.TextField()),
                ('speed', models.IntegerField(
                    choices=[(100, 'FASTEST'), (200, 'FASTER'), (300, 'FAST'), (400, 'NORMAL'),
                             (500, 'SLOW'), (600, 'SLOWER'), (700, 'SLOWEST')], default=400)),
                ('font_family', models.CharField(blank=True, max_length=100, null=True)),
                ('font_size',
                 models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('colour', models.CharField(blank=True, max_length=10, null=True)),
                ('outline', models.CharField(blank=True, max_length=10, null=True)),
                ('background', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TickerSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ticker Series',
                'verbose_name_plural': 'Ticker Series',
            },
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True,
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   parent_link=True, primary_key=True,
                                                   serialize=False, to='mediamanager.Asset')),
                ('media_file', models.FileField(storage=utils.files.DedupedMediaStorage(),
                                                upload_to=utils.files.md5_file_name)),
                ('checksum', models.CharField(editable=False, max_length=120)),
            ],
            options={
                'abstract': False,
            },
            bases=('mediamanager.asset',),
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True,
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   parent_link=True, primary_key=True,
                                                   serialize=False, to='mediamanager.Asset')),
                ('media_file', models.FileField(storage=utils.files.DedupedMediaStorage(),
                                                upload_to=utils.files.md5_file_name)),
                ('checksum', models.CharField(editable=False, max_length=120)),
            ],
            options={
                'abstract': False,
            },
            bases=('mediamanager.asset',),
        ),
        migrations.CreateModel(
            name='WebAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True,
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   parent_link=True, primary_key=True,
                                                   serialize=False, to='mediamanager.Asset')),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Web Asset',
                'verbose_name_plural': 'Web Asset',
            },
            bases=('mediamanager.asset',),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ticker_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='mediamanager.TickerSeries'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='mediamanager.Asset'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='mediamanager.Playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='items',
            field=models.ManyToManyField(through='mediamanager.PlaylistItem',
                                         to='mediamanager.Asset'),
        ),
        migrations.AddField(
            model_name='contentfeed',
            name='media_playlist',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='mediamanager.Playlist'),
        ),
        migrations.AddField(
            model_name='contentfeed',
            name='ticker_series',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='mediamanager.TickerSeries'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2016, 7, 21, 11, 59, 3, 477151,
                                                                 tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='ticker',
            name='background',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='colour',
            field=models.CharField(blank=True, default='#000000', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='font_family',
            field=models.CharField(blank=True, default='sans', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='font_size',
            field=models.DecimalField(blank=True, decimal_places=1, default=22, max_digits=4,
                                      null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='outline',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='contentfeed',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeedAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True,
                                                   on_delete=django.db.models.deletion.CASCADE,
                                                   parent_link=True, primary_key=True,
                                                   serialize=False, to='mediamanager.Asset')),
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              to='feedmanager.Feed')),
            ],
            bases=('mediamanager.asset',),
        ),
        migrations.AddField(
            model_name='playlist',
            name='auto_add_feeds',
            field=models.BooleanField(default=True),
        ),
    ]
