# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('mediamanager', '0001_squashed_0011_auto_20160807_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfeed',
            name='media_playlist',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='mediamanager.Playlist'),
        ),
        migrations.AlterField(
            model_name='contentfeed',
            name='ticker_series',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='mediamanager.TickerSeries'),
        ),
    ]
