# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 17:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mediamanager', '0003_auto_20160826_0327_squashed_0004_auto_20160828_1825'),
    ]

    operations = [
        migrations.CreateModel(
                name='WebAssetTemplate',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('name', models.CharField(
                            help_text='The template name is what users select on the frontennd '
                                      'so it should be descriptive.',
                            max_length=100)),
                    ('template', models.TextField(
                            help_text='This is the HTML template that will be rendered by the '
                                      'client and sent as a web asset.')),
                    ('variables', models.CharField(
                            help_text='The variables present in the template that will need to be '
                                      'filled in by the user in the frontend.',
                            max_length=200, validators=[
                                django.core.validators.RegexValidator('([\\w]*),? ?',
                                                                      'You need to enter one or '
                                                                      'more variable names '
                                                                      'separated by commas',
                                                                      'Invalid Variable List')])),
                ],
        ),
    ]
