# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mediamanager', '0004_webassettemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webassettemplate',
            options={'verbose_name': 'Web Asset Template'},
        ),
        migrations.AlterField(
            model_name='webassettemplate',
            name='variables',
            field=models.CharField(
                    help_text='The variables present in the template that will need to be '
                              'filled in by the user in the frontend.',
                max_length=200),
        ),
    ]
