# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models

import utils.files


class Migration(migrations.Migration):
    dependencies = [
        ('mediamanager', '0006_merge_20160929_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='media_file',
            field=models.FileField(upload_to=utils.files.md5_file_name),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='media_file',
            field=models.FileField(upload_to=utils.files.md5_file_name),
        ),
    ]
