# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mediamanager', '0007_auto_20170110_0200'),
    ]

    operations = [
        migrations.AddField(
                model_name='asset',
                name='thumbnail',
                field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
