# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mediamanager', '0008_asset_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
                name='CalendarAsset',
                fields=[
                    ('asset_ptr', models.OneToOneField(auto_created=True,
                                                       on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True,
                                                       serialize=False, to='mediamanager.Asset')),
                    ('url', models.CharField(max_length=255)),
                    ('data', models.TextField(blank=True, editable=False, null=True)),
                    ('last_update', models.DateTimeField(blank=True, editable=False, null=True)),
                ],
                bases=('mediamanager.asset',),
        ),
        migrations.AddField(
                model_name='webassettemplate',
                name='calendar_support',
                field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
                model_name='webassettemplate',
                name='name',
                field=models.CharField(
                        help_text='The template name is what users select on the frontend so it '
                                  'should be descriptive.',
                    max_length=100),
        ),
        migrations.AddField(
                model_name='calendarasset',
                name='template',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                        to='mediamanager.WebAssetTemplate'),
        ),
    ]
