# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 14:09from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mediamanager', '0009_auto_20170323_1804'),
    ]

    operations = [
        migrations.AlterField(
                model_name='asset',
                name='asset_url',
                field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
                model_name='asset',
                name='thumbnail',
                field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
                model_name='asset',
                name='type',
                field=models.CharField(editable=False, max_length=25),
        ),
    ]
