# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0011_webassettemplate_data_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='metadata',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='raw_metadata',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
