# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0013_auto_20171223_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='expire_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
