# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.files


class Migration(migrations.Migration):
    replaces = [('feedmanager', '0001_initial'), ('feedmanager', '0002_auto_20160713_0332'),
                ('feedmanager', '0003_auto_20160806_0320'),
                ('feedmanager', '0004_auto_20160806_2214'), ('feedmanager', '0005_feed_published'),
                ('feedmanager', '0006_feed_type')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('RANDOM', 'Random'), ('DATED', 'Dated')],
                                          max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='feedmanager.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_data', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='feedmanager.Category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='ImageFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True,
                                                  on_delete=django.db.models.deletion.CASCADE,
                                                  parent_link=True, primary_key=True,
                                                  serialize=False, to='feedmanager.Feed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='feedmanager.Category')),
            ],
            options={
                'abstract': False,
            },
            bases=('feedmanager.feed',),
        ),
        migrations.CreateModel(
            name='ImageSnippet',
            fields=[
                ('snippet_ptr', models.OneToOneField(auto_created=True,
                                                     on_delete=django.db.models.deletion.CASCADE,
                                                     parent_link=True, primary_key=True,
                                                     serialize=False, to='feedmanager.Snippet')),
                ('media', models.FileField(storage=utils.files.DedupedMediaStorage(),
                                           upload_to=utils.files.md5_file_name)),
                ('checksum', models.CharField(editable=False, max_length=120)),
            ],
            options={
                'abstract': False,
            },
            bases=('feedmanager.snippet',),
        ),
        migrations.CreateModel(
            name='VideoFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True,
                                                  on_delete=django.db.models.deletion.CASCADE,
                                                  parent_link=True, primary_key=True,
                                                  serialize=False, to='feedmanager.Feed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='feedmanager.Category')),
            ],
            options={
                'abstract': False,
            },
            bases=('feedmanager.feed',),
        ),
        migrations.CreateModel(
            name='VideoSnippet',
            fields=[
                ('snippet_ptr', models.OneToOneField(auto_created=True,
                                                     on_delete=django.db.models.deletion.CASCADE,
                                                     parent_link=True, primary_key=True,
                                                     serialize=False, to='feedmanager.Snippet')),
                ('media', models.FileField(storage=utils.files.DedupedMediaStorage(),
                                           upload_to=utils.files.md5_file_name)),
                ('checksum', models.CharField(editable=False, max_length=120)),
            ],
            options={
                'abstract': False,
            },
            bases=('feedmanager.snippet',),
        ),
        migrations.CreateModel(
            name='WebFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True,
                                                  on_delete=django.db.models.deletion.CASCADE,
                                                  parent_link=True, primary_key=True,
                                                  serialize=False, to='feedmanager.Feed')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='feedmanager.Template')),
            ],
            options={
                'abstract': False,
            },
            bases=('feedmanager.feed',),
        ),
        migrations.CreateModel(
            name='WebSnippet',
            fields=[
                ('snippet_ptr', models.OneToOneField(auto_created=True,
                                                     on_delete=django.db.models.deletion.CASCADE,
                                                     parent_link=True, primary_key=True,
                                                     serialize=False, to='feedmanager.Snippet')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('feedmanager.snippet',),
        ),
        migrations.AddField(
            model_name='feed',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='type',
            field=models.CharField(default='WEB', editable=False, max_length=25),
            preserve_default=False,
        ),
    ]
