# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 13:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedmanager', '0001_squashed_0006_feed_type'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='imagefeed',
                name='category',
        ),
        migrations.RemoveField(
                model_name='template',
                name='category',
        ),
        migrations.RemoveField(
                model_name='videofeed',
                name='category',
        ),
        migrations.AddField(
                model_name='feed',
                name='category',
                field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                        to='feedmanager.Category'),
                preserve_default=False,
        ),
    ]
