# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feedmanager', '0003_template_duration'),
    ]

    operations = [
        migrations.AlterField(
                model_name='template',
                name='duration',
                field=models.PositiveIntegerField(
                        default=10000,
                        help_text='How long should a slide using this template be visible on '
                                  'screen. <br/>If a template has an animation this time should '
                                  'ensure that the animation has enough time to complete. '),
        ),
    ]
