# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0001_initial'),
        ('feedmanager', '0004_auto_20160909_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='publish_to',
            field=models.ManyToManyField(to='client_manager.Client'),
        ),
    ]
