# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 21:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import utils.files


class Migration(migrations.Migration):
    dependencies = [
        ('feedmanager', '0004_auto_20160909_2257'),
    ]

    operations = [
        migrations.AlterField(
                model_name='category',
                name='name',
                field=models.CharField(
                        help_text='Enter a helpful name for this feed category. '
                                  'Example: <em>"Word of the Day"</em>',
                        max_length=100),
        ),
        migrations.AlterField(
                model_name='category',
                name='type',
                field=models.CharField(choices=[('RANDOM', 'Random'), ('DATED', 'Dated')],
                                       help_text='Select whether this option is time-sensitive or '
                                                 'not.For a time-sensitive category (e.g. "This '
                                                 'day in history"), only content relevant to the '
                                                 'current date will be fetched.',
                                       max_length=10),
        ),
        migrations.AlterField(
                model_name='feed',
                name='category',
                field=models.ForeignKey(
                        help_text='The feed category decides what snippets appear in this feed.',
                        on_delete=django.db.models.deletion.CASCADE, to='feedmanager.Category'),
        ),
        migrations.AlterField(
                model_name='feed',
                name='name',
                field=models.CharField(
                        help_text='This is a friendly name to identify this feed, it is not '
                                  'visible to end-users. ',
                        max_length=100),
        ),
        migrations.AlterField(
                model_name='feed',
                name='published',
                field=models.BooleanField(default=False,
                                          help_text='A feed that is published will appear in '
                                                    "users' asset lists. For a feed to be "
                                                    'published it needs to have a valid snippet.'),
        ),
        migrations.AlterField(
                model_name='feed',
                name='slug',
                field=models.SlugField(
                        help_text='This field should be filled in automatically based on the '
                                  'name. It is a simplified representation of the name such that '
                                  'it can be part of a URL.'),
        ),
        migrations.AlterField(
                model_name='imagesnippet',
                name='media',
                field=models.FileField(
                        help_text='This is the media file that will be served in the feed '
                                  'directly.',
                        storage=utils.files.DedupedMediaStorage(),
                        upload_to=utils.files.md5_file_name),
        ),
        migrations.AlterField(
                model_name='snippet',
                name='category',
                field=models.ForeignKey(
                        help_text='Select which category should display this snippet.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='feedmanager.Category'),
        ),
        migrations.AlterField(
                model_name='snippet',
                name='date',
                field=models.DateField(blank=True,
                                       help_text='Enter a date here if this snippet is '
                                                 'date-sensitive. This will only have an effect '
                                                 'if the snippet category itself is '
                                                 'date-sensitive.',
                                       null=True),
        ),
        migrations.AlterField(
                model_name='snippet',
                name='title',
                field=models.CharField(blank=True,
                                       help_text='Pick a good topic or title for the snippet. In '
                                                 'some cases this might be visible to end-users. ',
                                       max_length=255, null=True),
        ),
        migrations.AlterField(
                model_name='template',
                name='name',
                field=models.CharField(
                        help_text='This is just a friendly name to help you recognise the purpose '
                                  'of the template. It is not visible to users.',
                        max_length=100),
        ),
        migrations.AlterField(
                model_name='template',
                name='template_data',
                field=models.TextField(
                        help_text='This is the actual content of the template. The title and '
                                  'content snippets will be filled in here to render the final '
                                  'page that will be pushed to devices.'),
        ),
        migrations.AlterField(
                model_name='videosnippet',
                name='media',
                field=models.FileField(
                        help_text='This is the media file that will be served in the feed '
                                  'directly.',
                        storage=utils.files.DedupedMediaStorage(),
                        upload_to=utils.files.md5_file_name),
        ),
        migrations.AlterField(
                model_name='webfeed',
                name='template',
                field=models.ForeignKey(
                        help_text='Web feeds fill in the data from web snippets into this template '
                                  'to produce the final page that will be seen by on devices.',
                        on_delete=django.db.models.deletion.CASCADE, to='feedmanager.Template'),
        ),
        migrations.AlterField(
                model_name='websnippet',
                name='content',
                field=models.TextField(
                        help_text='This is the actual content of the web snippet. How and '
                                  'where it appears depends on the template used to render '
                                  'it. Some templates strip HTML content.'),
        ),
    ]
