# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('feedmanager', '0005_feed_publish_to'),
        ('feedmanager', '0005_auto_20160918_0306'),
    ]

    operations = [
    ]
