# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    replaces = [('devicemanager', '0001_initial'), ('devicemanager', '0002_auto_20160702_1120'),
                ('devicemanager', '0003_auto_20160713_0227'),
                ('devicemanager', '0004_auto_20160721_1729'),
                ('devicemanager', '0005_auto_20160728_2311'),
                ('devicemanager', '0006_auto_20160803_0423'),
                ('devicemanager', '0007_auto_20160809_0409')]

    initial = True

    dependencies = [
        ('mediamanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('last_ping', models.DateTimeField()),
                ('debug_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feed', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.SET_NULL,
                                           to='mediamanager.ContentFeed')),
            ],
            options={
                'verbose_name': 'Device Group',
                'verbose_name_plural': 'Device Groups',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='devicemanager.DeviceGroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_ping',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
