# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [('devicemanager', '0002_auto_20160826_0327'),
                ('devicemanager', '0003_auto_20160828_1825')]

    dependencies = [
        ('client_manager', '0001_initial'),
        ('devicemanager', '0001_squashed_0007_auto_20160809_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='client_manager.Client'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='client_manager.Client'),
        ),
    ]
