# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0001_initial'),
        ('devicemanager', '0002_auto_20160826_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='site',
        ),
        migrations.RemoveField(
            model_name='devicegroup',
            name='site',
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='client_manager.Client'),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='client_manager.Client'),
        ),
    ]
