# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devicemanager', '0002_auto_20160826_0327_squashed_0003_auto_20160828_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='build_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
