# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicemanager', '0002_auto_20160702_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
