# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models

import devicemanager.models


class Migration(migrations.Migration):
    dependencies = [
        ('devicemanager', '0003_device_build_version'),
    ]

    operations = [
        migrations.CreateModel(
                name='AppBuild',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('version_code', models.PositiveIntegerField(
                            help_text='The version of code of the Android application. This value '
                                      'should always increase. The app build with the highest '
                                      'version will be pused to the devices.')),
                    ('app_build', models.FileField(
                            help_text='The app APK file.',
                            upload_to=devicemanager.models.build_upload_location)),
                    ('checksum', models.CharField(editable=False, max_length=120)),
                ],
        ),
        migrations.AlterField(
                model_name='device',
                name='build_version',
                field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
