# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devicemanager', '0003_auto_20160713_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_ping',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
