# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 06:48
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0009_client_update_interval'),
        ('devicemanager', '0007_device_command'),
    ]

    operations = [
        migrations.CreateModel(
                name='MirrorServer',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('name',
                     models.CharField(help_text='A name for the mirror server.', max_length=255)),
                    ('mirror_id', models.UUIDField(editable=False)),
                    ('address', models.CharField(blank=True,
                                                 help_text='The local address of the mirror at '
                                                           'which devices can connect to it.',
                                                 max_length=255, null=True)),
                    ('last_ping',
                     models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                    ('owner', models.ForeignKey(blank=True, null=True,
                                                on_delete=django.db.models.deletion.SET_NULL,
                                                to='client_manager.Client')),
                ],
        ),
        migrations.AddField(
                model_name='devicegroup',
                name='mirror',
                field=models.ForeignKey(blank=True, null=True,
                                        on_delete=django.db.models.deletion.CASCADE,
                                        to='devicemanager.MirrorServer'),
        ),
    ]
