# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devicemanager', '0009_auto_20170509_1529'),
    ]

    operations = [
        migrations.AlterField(
                model_name='device',
                name='command',
                field=models.CharField(blank=True, choices=[('reboot', 'Reboot Device'),
                                                            ('free-space', 'Delete Unused Media'),
                                                            ('clear-media',
                                                             'Clear All Device Media'),
                                                            ('reset-device', 'Reset Device'),
                                                            ('change-realm:dev',
                                                             'Device Realm: development'),
                                                            ('change-realm:stage',
                                                             'Device Realm: staging'),
                                                            ('change-realm:live',
                                                             'Device Realm: live'),
                                                            ('screenshot', 'Take screenshot'),
                                                            ('screenshot:burst',
                                                             'Take screenshot burst')],
                                       max_length=20, null=True),
        ),
    ]
