# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devicemanager', '0010_auto_20170511_1549'),
    ]

    operations = [
        migrations.AddField(
                model_name='devicescreenshot',
                name='thumbnail',
                field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
