# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devicemanager', '0011_devicescreenshot_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
                model_name='appbuild',
                name='version_code',
                field=models.PositiveIntegerField(
                        help_text='The version of code of the Android application. This value should '
                                  'always increase. The app build with the highest version will be '
                                  'pushed to the devices.'),
        ),
    ]
