# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 07:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mediamanager', '0010_auto_20170407_1939'),
        ('devicemanager', '0012_auto_20170604_1731'),
    ]

    operations = [
        migrations.CreateModel(
                name='PriorityMessage',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('activated_on', models.DateTimeField(blank=True, null=True)),
                    ('duration', models.IntegerField(blank=True,
                                                     choices=[(0, 'Indefinite'), (15, '15 Minutes'),
                                                              (30, '30 Minutes'),
                                                              (45, '45 Minutes'),
                                                              (60, '60 Minutes')], null=True)),
                    ('device_group',
                     models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                          to='devicemanager.DeviceGroup')),
                    ('message', models.ForeignKey(blank=True, null=True,
                                                  on_delete=django.db.models.deletion.CASCADE,
                                                  to='mediamanager.Asset')),
                ],
        ),
    ]
