# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 23:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('devicemanager', '0007_device_command'),
        ('mediamanager', '0007_auto_20170110_0200'),
    ]

    operations = [
        migrations.CreateModel(
                name='ScheduledContent',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('day', models.CharField(
                            choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'),
                                     ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'),
                                     ('sun', 'Sunday')], max_length=4)),
                    ('default', models.BooleanField()),
                    ('start_time', models.TimeField(blank=True, null=True)),
                    ('end_time', models.TimeField(blank=True, null=True)),
                    ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='mediamanager.ContentFeed')),
                    ('device_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                       to='devicemanager.DeviceGroup')),
                ],
                options={
                    'verbose_name': 'Scheduled Content',
                    'verbose_name_plural': 'Scheduled Content',
                },
        ),
        migrations.CreateModel(
                name='SpecialContent',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('date', models.DateField()),
                    ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='mediamanager.ContentFeed')),
                    ('device_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                       to='devicemanager.DeviceGroup')),
                ],
                options={
                    'verbose_name_plural': 'Special Content',
                },
        ),
        migrations.AlterUniqueTogether(
                name='specialcontent',
                unique_together=set([('device_group', 'date')]),
        ),
    ]
