# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedule_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
                name='scheduledcontent',
                options={'ordering': ('-default', 'start_time'),
                         'verbose_name': 'Scheduled Content',
                         'verbose_name_plural': 'Scheduled Content'},
        ),
        migrations.AlterModelOptions(
                name='specialcontent',
                options={'ordering': ('date',), 'verbose_name_plural': 'Special Content'},
        ),
        migrations.AlterField(
                model_name='scheduledcontent',
                name='default',
                field=models.BooleanField(default=False),
        ),
    ]
