# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:29
from __future__ import unicode_literals

import django.db.models.deletion
import storages.backends.s3boto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name='Post',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('title', models.CharField(max_length=255)),
                    ('body', models.TextField()),
                    ('posted_on', models.DateTimeField(auto_now_add=True)),
                ],
        ),
        migrations.CreateModel(
                name='PostTopic',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('name', models.CharField(max_length=24)),
                    ('image', models.ImageField(storage=storages.backends.s3boto.S3BotoStorage(),
                                                upload_to='')),
                ],
        ),
        migrations.CreateModel(
                name='UserPostStatus',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('notified_on', models.DateTimeField(blank=True, null=True)),
                    ('read_on', models.DateTimeField(blank=True, null=True)),
                    ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='notification_manager.Post')),
                    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to=settings.AUTH_USER_MODEL)),
                ],
        ),
        migrations.AddField(
                model_name='post',
                name='topic',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                        to='notification_manager.PostTopic'),
        ),
    ]
