# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:21
from __future__ import unicode_literals

import django.db.models.deletion
import storages.backends.s3boto
from django.conf import settings
from django.db import migrations, models

import notification_manager.models


class Migration(migrations.Migration):
    replaces = [('notification_manager', '0001_initial'),
                ('notification_manager', '0002_auto_20171102_0616'),
                ('notification_manager', '0003_remove_userpoststatus_notified_on'),
                ('notification_manager', '0004_auto_20171103_2045')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name='Post',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True,
                                            serialize=False, verbose_name='ID')),
                    ('title', models.CharField(max_length=255)),
                    ('body', models.TextField()),
                    ('posted_on', models.DateTimeField(auto_now_add=True)),
                ],
        ),
        migrations.CreateModel(
                name='PostTopic',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True,
                                            serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=24)),
                    ('image',
                     models.ImageField(storage=storages.backends.s3boto.S3BotoStorage(),
                                       upload_to=notification_manager.models.post_topic_icon_location)),
                ],
        ),
        migrations.CreateModel(
                name='UserPostStatus',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True,
                                            serialize=False, verbose_name='ID')),
                    ('read_on', models.DateTimeField(blank=True, null=True)),
                    ('post',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                       to='notification_manager.Post')),
                    ('user',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL)),
                ],
        ),
        migrations.AddField(
                model_name='post',
                name='topic',
                field=models.ForeignKey(help_text='Topics let you organise posts.',
                                        on_delete=django.db.models.deletion.CASCADE,
                                        to='notification_manager.PostTopic'),
        ),
        migrations.AlterUniqueTogether(
                name='userpoststatus',
                unique_together=set([('user', 'post')]),
        ),
        migrations.AlterField(
                model_name='post',
                name='body',
                field=models.TextField(
                    help_text='The main body of the text in Markdown format. It will be rendered to HTML before being displayed to users.'),
        ),
        migrations.AlterField(
                model_name='post',
                name='title',
                field=models.CharField(
                    help_text='A title for this post. The title should be short, and to the point.',
                    max_length=255),
        ),
    ]
