# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_manager', '0001_squashed_0004_auto_20171103_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_on']},
        ),
    ]
