# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('notification_manager', '0002_auto_20171102_0616'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='userpoststatus',
                name='notified_on',
        ),
    ]
