# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notification_manager', '0003_remove_userpoststatus_notified_on'),
    ]

    operations = [
        migrations.AlterField(
                model_name='post',
                name='body',
                field=models.TextField(
                    help_text='The main body of the text in Markdown format. It will be rendered to HTML before being displayed to users.'),
        ),
        migrations.AlterField(
                model_name='post',
                name='title',
                field=models.CharField(
                    help_text='A title for this post. The title should be short, and to the point.',
                    max_length=255),
        ),
        migrations.AlterField(
                model_name='post',
                name='topic',
                field=models.ForeignKey(help_text='Topics let you organise posts.',
                                        on_delete=django.db.models.deletion.CASCADE,
                                        to='notification_manager.PostTopic'),
        ),
    ]
