# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='display_device_logo',
            field=models.BooleanField(default=True),
        ),
    ]
