# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 21:21
from __future__ import unicode_literals

import storages.backends.s3boto
from django.db import migrations, models

import client_manager.models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0005_client_app_build_channel'),
    ]

    operations = [
        migrations.AlterField(
                model_name='client',
                name='device_logo',
                field=models.ImageField(blank=True,
                                        help_text='A logo of the client for use on the device. If no device logo is provided, the main logo will be used.',
                                        null=True, storage=storages.backends.s3boto.S3BotoStorage(),
                                        upload_to=client_manager.models.upload_location_device_logo),
        ),
        migrations.AlterField(
                model_name='client',
                name='logo',
                field=models.ImageField(help_text='A logo of the client for use in the frontend.',
                                        storage=storages.backends.s3boto.S3BotoStorage(),
                                        upload_to=client_manager.models.upload_location_logo),
        ),
    ]
