# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:32
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0006_auto_20170305_0251'),
    ]

    operations = [
        migrations.CreateModel(
                name='ClientSubscriptionData',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('activation_date', models.DateField(default=datetime.datetime.now)),
                    ('renewal_date', models.DateField(default=datetime.datetime.now)),
                ],
                options={
                    'verbose_name': 'Client Subscription Data',
                    'verbose_name_plural': 'Client Subscription Data',
                },
        ),
        migrations.AddField(
                model_name='client',
                name='financial_contact_email',
                field=models.EmailField(blank=True,
                                        help_text='E-Mail address of financial contact.',
                                        max_length=100, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='financial_contact_name',
                field=models.CharField(blank=True, help_text='Name of financial contact.',
                                       max_length=100, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='organisation_address',
                field=models.CharField(blank=True, help_text='Primary address of the organisation',
                                       max_length=255, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='organisation_name',
                field=models.CharField(blank=True, help_text='Name of the organisation',
                                       max_length=100, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='primary_contact_email',
                field=models.EmailField(blank=True, help_text='E-Mail address of primary contact.',
                                        max_length=254, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='primary_contact_name',
                field=models.CharField(blank=True, help_text='Name of primary contact.',
                                       max_length=100, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='primary_contact_phone',
                field=models.CharField(blank=True, help_text='Phone number of primary contact.',
                                       max_length=100, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='technical_contact_email',
                field=models.EmailField(blank=True,
                                        help_text='E-Mail address of technical contact.',
                                        max_length=254, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='technical_contact_name',
                field=models.CharField(blank=True, help_text='Name of technical contact.',
                                       max_length=100, null=True),
        ),
        migrations.AddField(
                model_name='clientsubscriptiondata',
                name='client',
                field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='subscription', to='client_manager.Client'),
        ),
    ]
