# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0007_auto_20170316_2202'),
    ]

    operations = [
        migrations.AddField(
                model_name='client',
                name='financial_contact_phone',
                field=models.CharField(blank=True, help_text='Phone number of financial contact.',
                                       max_length=100, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='technical_contact_phone',
                field=models.CharField(blank=True, help_text='Phone number of technical contact.',
                                       max_length=100, null=True),
        ),
        migrations.AlterField(
                model_name='client',
                name='app_build_channel',
                field=models.ForeignKey(blank=True,
                                        help_text='All devices owned by this client will receive updates published to this channel.',
                                        null=True, on_delete=django.db.models.deletion.CASCADE,
                                        to='devicemanager.AppBuildChannel'),
        ),
    ]
