# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 14:09from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0008_auto_20170322_0229'),
    ]

    operations = [
        migrations.AddField(
                model_name='client',
                name='update_interval',
                field=models.DurationField(default=datetime.timedelta(0, 120),
                                           help_text='How often should devices check for updates'),
        ),
    ]
