# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0009_client_update_interval'),
    ]

    operations = [
        migrations.AddField(
                model_name='client',
                name='device_logo_checksum',
                field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
        migrations.AddField(
                model_name='client',
                name='logo_checksum',
                field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
