# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 12:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0010_auto_20170606_1355'),
    ]

    operations = [
        migrations.CreateModel(
                name='ClientSettings',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('idle_detection_enabled', models.BooleanField(default=False,
                                                                   help_text='Should the app auto-launch during idleperiods.')),
                    ('idle_detection_threshold', models.PositiveSmallIntegerField(
                        help_text='How long (in minutes) should the device be idle before the app is launched.')),
                    ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='settings',
                                                    to='client_manager.Client')),
                ],
        ),
    ]
