# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0011_clientsettings'),
    ]

    operations = [
        migrations.AlterField(
                model_name='clientsettings',
                name='idle_detection_enabled',
                field=models.BooleanField(default=False,
                                          help_text='Should the app auto-launch during idle periods.'),
        ),
        migrations.AlterField(
                model_name='clientsettings',
                name='idle_detection_threshold',
                field=models.PositiveSmallIntegerField(default=15,
                                                       help_text='How long (in minutes) should the device be idle before the app is launched.'),
        ),
    ]
