# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 20:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0012_auto_20170618_1816'),
    ]

    operations = [
        migrations.CreateModel(
                name='Features',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                            verbose_name='ID')),
                    ('screenshots', models.BooleanField(default=False,
                                                        help_text='Enables or disable the screenshot feature for the client.')),
                    ('smart_notice_board', models.BooleanField(default=False,
                                                               help_text='Enabled or disables smart notice board support. This includes support for the Windows client with idle detection, scheduled launching, and push messaging.')),
                    ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='features',
                                                    to='client_manager.Client')),
                ],
        ),
    ]
