# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 20:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_manager', '0013_features'),
    ]

    operations = [
        migrations.AlterField(
                model_name='clientuserprofile',
                name='user',
                field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
